### PR TITLE
This gem is now compatible with Rails versions: 3.2 4.0 4.1 4.2

### PR DESCRIPTION
**Pull request by thejamespinto**

### CODE REVIEW

**Comment by jejacks0n** [comment]
Nice!

**Comment by thejamespinto** [comment]
I'll get it right ;)

**Comment by jejacks0n** [comment]
No worries, I appreciate the contributions. =)

**Comment by thejamespinto** [comment]
@jejacks0n I'm magical, please commit now ;)

**Comment by thejamespinto** [comment]
@jejacks0n ping

**Comment by jejacks0n** [comment]
Sorry man, give me a bit -- been busy and burned out. Will try sometime this week, but am mostly unplugged.

---
Jeremy Jackson
303-507-6846

**Pull request closed without merging**
