### PR TITLE
Remove comma from Buenos_Aires timezone name

### PR DESCRIPTION
**Pull request by mschartman**

### CODE REVIEW

**Comment by jejacks0n** [comment]
Whoa! I didn't know anybody used this. =)

Thanks for the PR.

**Comment by mschartman** [comment]
No problem! We do use it :) Lots of new users from Argentina lately, so we ran into this. Do you think you could push a new version up to RubyGems?

**Comment by jejacks0n** [comment]
0.2.4 released.

**Comment by mschartman** [comment]
Awesome, thanks!

**Pull request merged**
